# Run this
# XAUTH_TOKEN=`xauth list` docker-compose up --build
version: "3.7"
services:
  viewer:
    build: 
      context: data_generation
      network: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: |-
      bash -c '
        xauth add ${XAUTH_TOKEN}; 
        tail -f /dev/null
      '
    container_name: data_generation