version: "3.7"
services:
  viewer:
    build: 
      context: data_generation
      network: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: /data_generation/build/bin/viewer
    container_name: data_generation